# Generated by Django 3.0 on 2025-12-13 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20251116_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='number',
        ),
    ]
