# Generated by Django 3.0 on 2026-02-21 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_complaint_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordermain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.CharField(max_length=200)),
                ('Date', models.DateField(max_length=500)),
                ('Status', models.CharField(max_length=500)),
                ('BUYING_USERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='myapp.Users')),
                ('PRODUCT_OWNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='myapp.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Ordersub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=200)),
                ('ORDERMAIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Ordermain')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Product')),
            ],
        ),
    ]
