# Generated by Django 3.0 on 2025-11-15 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alert_cart_complaint_forestofficer_product_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='forestofficer',
            name='FORESTSTATION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Foreststation'),
            preserve_default=False,
        ),
    ]
