# Generated by Django 3.0 on 2025-11-16 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_forestofficer_foreststation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detect_Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('anima_lname', models.CharField(max_length=500)),
                ('animal_image', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='alert',
            name='AURH_USER',
        ),
        migrations.AddField(
            model_name='alert',
            name='OFFICER',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapp.Forestofficer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='message',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
