# Generated by Django 3.0 on 2025-11-16 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20251116_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detect_alert',
            old_name='anima_lname',
            new_name='animal_name',
        ),
    ]
