# Generated by Django 3.0 on 2025-11-16 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20251116_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='OFFICER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Forestofficer'),
        ),
    ]
